---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:rknt/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: rknt/podinfo
      tag: 0.4.11
    replicaCount: 3
